### ISSUE TITLE
problem with verilator

### ISSUE THREAD

**Issue by H0sseinR0stami** [aebeljs/VeRLPy#4] opened 2022-07-27 09:00 UTC
Hi. I tried to re run your project but Verilator simulator dose not work properly. which version did you use?
Is there any way to provide me with working version?
best regards

**Comment by aebeljs** [comment] 2022-07-27 15:07
Hi @H0sseinR0stami, the Verilator version we used to test was `Verilator 4.038 2020-07-11 rev v4.038`. It should be available on Verilator's official website/package repository. Try this URL for instance: https://repology.org/project/verilator/versions.

Thanks,
Aebel

**Comment by ssmolov** [comment] 2022-09-07 13:41
Dear colleagues, I probably have similar issue. I've successfully installed VeRLPy through pip, but when I try to make the axi_fabric_rl example, I receive the following:
```
ODULE=test_axi_fabric TESTCASE= TOPLEVEL=mkaxi4_fabric_test TOPLEVEL_LANG=verilog \
         sim_build/Vtop 
     -.--ns INFO     cocotb.gpi                         ..mbed/gpi_embed.cpp:76   in set_program_name_in_venv        Did not detect Python virtual environment. Using system-wide Python interpreter
     -.--ns INFO     cocotb.gpi                         ../gpi/GpiCommon.cpp:99   in gpi_print_registered_impl       VPI registered
     0.00ns INFO     Running on Verilator version 4.226 2022-08-31
     0.00ns INFO     Running tests with cocotb v1.6.2 from /home/ssedai/.local/lib/python3.8/site-packages/cocotb
     0.00ns INFO     Seeding Python random module with 1662557428
     0.00ns CRITICAL Failed to import module test_axi_fabric: No module named 'cocotb.drivers'
     0.00ns INFO     MODULE variable was "test_axi_fabric"
     0.00ns INFO     Traceback: 
     0.00ns INFO     Traceback (most recent call last):
                       File "/home/ssedai/.local/lib/python3.8/site-packages/cocotb/regression.py", line 172, in _discover_tests
                         module = _my_import(module_name)
                       File "/home/ssedai/.local/lib/python3.8/site-packages/cocotb/regression.py", line 66, in _my_import
                         mod = __import__(name)
                       File "/home/ssedai/.local/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
                         exec(co, module.__dict__)
                       File "/home/ssedai/ai/VeRLPy/examples/axi4_fabric_rl/test_axi_fabric.py", line 6, in <module>
                         from test_axi_fabric_helper import *
                       File "/home/ssedai/.local/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
                         exec(co, module.__dict__)
                       File "/home/ssedai/ai/VeRLPy/examples/axi4_fabric_rl/test_axi_fabric_helper.py", line 3, in <module>
                         from cocotb.drivers import BusDriver
                     ModuleNotFoundError: No module named 'cocotb.drivers'
                     
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/home/ssedai/.local/lib/python3.8/site-packages/cocotb/__init__.py", line 242, in _initialise_testbench
    _initialise_testbench_(argv_)
  File "/home/ssedai/.local/lib/python3.8/site-packages/cocotb/__init__.py", line 344, in _initialise_testbench_
    regression_manager = RegressionManager.from_discovery(top)
  File "/home/ssedai/.local/lib/python3.8/site-packages/cocotb/regression.py", line 147, in from_discovery
    return cls(dut, tests)
  File "/home/ssedai/.local/lib/python3.8/site-packages/cocotb/regression.py", line 126, in __init__
    for test in tests:
  File "/home/ssedai/.local/lib/python3.8/site-packages/cocotb/regression.py", line 172, in _discover_tests
    module = _my_import(module_name)
  File "/home/ssedai/.local/lib/python3.8/site-packages/cocotb/regression.py", line 66, in _my_import
    mod = __import__(name)
  File "/home/ssedai/.local/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/home/ssedai/ai/VeRLPy/examples/axi4_fabric_rl/test_axi_fabric.py", line 6, in <module>
    from test_axi_fabric_helper import *
  File "/home/ssedai/.local/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/home/ssedai/ai/VeRLPy/examples/axi4_fabric_rl/test_axi_fabric_helper.py", line 3, in <module>
    from cocotb.drivers import BusDriver
ModuleNotFoundError: No module named 'cocotb.drivers'
     0.00ns ERROR    Failing test at simulator request before test run completion: Simulator shutdown prematurely
- /home/ssedai/.local/lib/python3.8/site-packages/cocotb/share/lib/verilator/verilator.cpp:118: Verilog $finish
ERROR: results.xml was not written by the simulation!
```
I've tried to use Verilator  4.038, but cocotb requires Verilator 4.106 or later. Verilator 4.106 gives me the error I've described above.

**Comment by ssmolov** [comment] 2022-09-07 14:16
Sorry, I missed top error message. The cause is that some modules in cocotb are migrated from cocotb package to cocotb_bus package. Being fixed, AXI example runs properly:)

**Comment by aebeljs** [comment] 2022-10-05 19:26
Thanks @ssmolov for pointing it out and raising the pull request for the fix! :)

Links to the breaking changes for future reference: https://github.com/cocotb/cocotb/pull/2289 , https://docs.cocotb.org/en/stable/release_notes.html#id14

Closing this issue since it seems resolved unless there are any other concerns.

**Closed by aebeljs** 2022-10-05 19:26 UTC
